# Generated by Django 4.1.3 on 2023-01-10 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Characters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('download_date', models.DateTimeField()),
                ('characters_file', models.FileField(unique=True, upload_to='collections')),
            ],
        ),
    ]
